SODP.UI/ViewModels/StagesViewModel.cs
using SODP.Domain.DTO;
using SODP.Domain.Models;
using System.Collections.Generic;

namespace SODP.UI.ViewModels
{
    public class StagesViewModel
    {
        public IList<StageDTO> Stages { get; set; }
        public PageInfo PageInfo { get; set; }
    }
}

SODP.UI/Areas/Stages/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SODP.Domain.Services;
using SODP.Model;
using SODP.UI.Pages.Shared;
using System.Threading.Tasks;


namespace SODP.UI.Areas.Stages.Pages
{
    public class IndexModel : SODPPageModel
    {
        private readonly IStagesService _stagesService;

        public IndexModel(IStagesService stagesService)
        {
            _stagesService = stagesService;
            ReturnUrl = "/Stages";
        }

        [BindProperty]
        public ServicePageResponse<Stage> Stages { get; set; }

        public async Task OnGet()
        {
            Stages = await _stagesService.GetAllAsync();
        }

        public async Task<IActionResult> OnPostDelete(string sign)
        {
            var response = await _stagesService.DeleteAsync(sign);
            if (!response.Success)
            {
                Stages = await _stagesService.GetAllAsync();
                return Page();
            }

            return RedirectToPage("Index");
        }
    }
}

SODP.UI/Pages/Stages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using SODP.Domain.DTO;
using SODP.Domain.Models;
using SODP.Domain.Services;
using SODP.UI.Pages.Shared;
using SODP.UI.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SODP.UI.Pages.Stages
{
    [Authorize(Roles = "Administrator, ProjectManager")]
    public class IndexModel : SODPPageModel
    {
        private readonly IStagesService _stagesService;
        const string partialViewName = "_StagePartialView";

        public IndexModel(IStagesService stagesService)
        {
            _stagesService = stagesService;
            ReturnUrl = "/Stages";
        }

        [BindProperty]
        public StagesViewModel StagesViewModel { get; set; }

        public async Task<IActionResult> OnGetAsync(int currentPage = 1, int pageSize = 15)
        {
            var url = new StringBuilder();
            url.Append("/Stages?currentPage=:&pageSize=");
            url.Append(pageSize.ToString());

            StagesViewModel = new StagesViewModel
            {
                PageInfo = new PageInfo
                {
                    CurrentPage = currentPage,
                    ItemsPerPage = pageSize,
                    Url = url.ToString()
                },
            };
            StagesViewModel.Stages = await GetStagesAsync(StagesViewModel.PageInfo);

            return Page();
        }


        public async Task<PartialViewResult> OnGetStageDetailsAsync(int? id)
        {
            var stage = (id == null) ? new StageDTO() : (await _stagesService.GetAsync((int)id)).Data;
            var partialViewResult = new PartialViewResult
            {
                ViewName = partialViewName,
                ViewData = new ViewDataDictionary<StageDTO>(ViewData, stage)
            };

            return await Task.FromResult(partialViewResult);
        }

        public async Task<PartialViewResult> OnPostStageDetailsAsync(StageDTO stage)
        {
            if (ModelState.IsValid)
            {
                var response = (stage.Id == 0) ? await _stagesService.CreateAsync(stage) : await _stagesService.UpdateAsync(stage);
                if (!response.Success)
                {
                    foreach(var error in response.ValidationErrors)
                    {
                        ModelState.AddModelError(error.Key, error.Value);
                    }
                }
            }

            var partialViewResult = new PartialViewResult
            {
                ViewName = partialViewName,
                ViewData = new ViewDataDictionary<StageDTO>(ViewData, stage)
            };

            return partialViewResult;
        }

        private async Task<IList<StageDTO>> GetStagesAsync(PageInfo pageInfo)
        {
            var serviceResponse = await _stagesService.GetAllAsync(pageInfo.CurrentPage, pageInfo.ItemsPerPage);
            pageInfo.TotalItems = serviceResponse.Data.TotalCount;
            pageInfo.CurrentPage = serviceResponse.Data.PageNumber;

            return serviceResponse.Data.Collection.ToList();
        }
    }
}

SODP.UI/Pages/Stages/Index.cshtml
@page
@model IndexModel

@{
    ViewData["Title"] = "Stadia";
}
@using Microsoft.AspNetCore.Identity
@using SODP.Model
@inject SignInManager<User> SignInManager

<br />
<div class="container row p-0 m-0">
    <div class="col-8">
        <h2 class="text-info">Stadia projektowe</h2>
    </div>
    @if (SignInManager.IsSignedIn(User))
    {
        <div id="modal-placeholder"></div>
        <div class="col-4 justify-content-end">
            <span data-toggle="tooltip" data-placement="top" title="Nowe stadium">
                <button type="button"
                        class="btn btn-info form-control text-white float-right"
                        title="Nowe stadium"
                        data-toggle="ajax-modal"
                        data-url="@Url.Page("Index","StageDetails")">
                    <i class="fas fa-plus"></i>&nbsp;&nbsp;&nbsp;Nowe stadium
                </button>
            </span>
        </div>
    }

    <div id="StageTable" class="col-12 p-3 mt-3">
        <form method="post">
            @if (Model.StagesViewModel.Stages.Count() > 0)
            {
                <table class="table table-sm table-hover">
                    <thead class="thead-light">
                        <tr>
                            <th>Symbol</th>
                            <th>Opis</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var stage in Model.StagesViewModel.Stages)
                        {
                            <tr>
                                <td>
                                    <a onclick='OpenStageEdit(@stage.Id)' 
                                       data-toggle="tooltip"
                                       data-placement="top"
                                       title="Edycja stadium">
                                    @stage.Sign</a>
                                </td>
                                <td>
                                    <a onclick='OpenStageEdit(@stage.Id)'
                                       data-toggle="tooltip"
                                       data-placement="top"
                                       title="Edycja stadium">
                                    @stage.Title</a>
                                </td>
                                <td>
                                    <div class="row group justify-content-end mr-0">
                                        <div>
                                            <a onclick='DeleteStage("/api/Stages/@stage.Id")'
                                               class="btn btn-lg mb-0 mt-0 ml-1 mr-1 p-1 text-danger"
                                               data-toggle="tooltip"
                                               data-placement="top"
                                               title="Usuń stadium">
                                                <i class="fas fa-trash-alt"></i>
                                            </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                        <tr>
                            <td colspan="3" class="text-right">
                                <div page-model="@Model.StagesViewModel.PageInfo" asp-action="Index" page-class="btn border"
                                     page-class-normal="btn btn-light" page-class-selected="btn btn-info active" class="btn-group">
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            }
            else
            {
                <p> Lista stadiów jest pusta</p>
            }
        </form>
    </div>
</div>

@section Scripts{
    <script src="~/js/delete.js"></script>
    <script src="~/js/stageList.js"></script>

    <script>
        function DeleteStage(url) {
            Delete(url);
        }
    </script>

    <script>
        function OpenStageEdit(currentId) {
            $.ajax({
                type: "Get",
                url: '@Url.Page("Index","StageDetails")&Id=' + currentId,
                success: function (data) {
                    $('#modal-placeholder').html(data);
                    $('#editstage').modal('show');
                }
            })
        }
    </script>
}

SODP.UI/Pages/Stages/_StagePartialView.cshtml
@model StageDTO

<!-- Modal -->
<div class="modal fade" id="editstage" tabindex="-1" role="dialog" aria-labelledby="editStageLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="text-info" id="editStageLabel">@(Model.Id==0 ? "Nowe" : "Edycja") stadium</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                <div id="error-placeholder"></div>
                <form asp-page-handler="StageDetails">
                    <input name="IsValidate" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <input asp-for="Id" type="hidden" value="@Model.Id"/>
                    <div class="form-group">
                        <input asp-for="Sign" id="sign" class="form-control" value="@Model.Sign" placeholder="Znak stadium" readonly="@(Model.Id.Equals(0) ? false : true)" />
                        <span asp-validation-for="Sign" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input asp-for="Title" id="title" class="form-control" value="@Model.Title" placeholder="Opis stadium" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <partial name="_SubmitAndBackButtonModalPartial" />
            </div>
        </div>
    </div>
</div>