SODP.UI/Pages/ActiveProjects/CreateUpdate.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SODP.Domain.DTO;
using SODP.Domain.Models;
using SODP.Domain.Services;
using SODP.UI.Pages.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SODP.UI.Pages.ActiveProjects
{
    [Authorize(Roles = "Administrator,ProjectManager")]
    public class CreateUpdateModel : SODPPageModel
    {
        private readonly IStagesService _stagesService;
        private readonly IProjectsService _projectsService;

        public CreateUpdateModel(IProjectsService projectsService, IStagesService stagesService)
        {
            _projectsService = projectsService;
            _stagesService = stagesService;
        }

        [BindProperty]
        public ProjectDTO Project { get; set; }

        public IEnumerable<SelectListItem> Stages { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                var stagesResponse = await _stagesService.GetAllAsync(1,0);
                Stages = stagesResponse.Data.Collection.Select(x => new SelectListItem()
                {
                    Value = x.Id.ToString(),
                    Text = $"({x.Sign.Trim()}) {x.Title.Trim()}"
                }).ToList();

                Project = new ProjectDTO();

                return Page();
            }

            var response = await _projectsService.GetAsync((int)id);
            if (response == null)
            {
                return NotFound();
            }
            Project = response.Data;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var stagesResponse = await _stagesService.GetAllAsync(1, 0);
            Stages = stagesResponse.Data.Collection.Select(x => new SelectListItem()
            {
                Value = x.Id.ToString(),
                Text = $"({x.Sign.Trim()}) {x.Title.Trim()}"
            }).ToList();

            if (ModelState.IsValid)
            {
                ServiceResponse response;

                if (Project.Id.Equals(0))
                {
                    var project = new ProjectDTO
                    {
                        Number = Project.Number,
                        StageId = Project.StageId,
                        Title = Project.Title,
                        Description = Project.Description
                    };
                    response = await _projectsService.CreateAsync(project);
                }
                else
                {
                    var project = new ProjectDTO
                    {
                        Id = Project.Id,
                        Number = Project.Number,
                        StageId = Project.StageId,
                        Title = Project.Title,
                        Description = Project.Description
                    };
                    response = await _projectsService.UpdateAsync(project);
                }

                if (!response.Success)
                {
                    return Page();
                }

                return RedirectToPage("Index");
            }
          
            return Page();
        }
    }
}

SODP.UI/Pages/ActiveProjects/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using SODP.Domain.DTO;
using SODP.Domain.Models;
using SODP.Domain.Services;
using SODP.UI.Pages.Shared;
using SODP.UI.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SODP.UI.Pages.ActiveProjects
{
    [Authorize(Roles = "User, Administrator, ProjectManager")]
    public class IndexModel : SODPPageModel
    {
        private readonly IProjectsService _projectsService;
        private readonly IStagesService _stagesService;
        const string partialViewName = "_ProjectPartialView";

        public IndexModel(IProjectsService projectsService, IStagesService stagesService)
        {
            _projectsService = projectsService;
            _stagesService = stagesService;
            ReturnUrl = "/ActiveProjects";
        }

        public ServicePageResponse<ProjectDTO> Projects { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            Projects = await _projectsService.GetAllAsync(0,0);

            return Page();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var response = await _projectsService.DeleteAsync(id);
            if (!response.Success)
            {
                Projects = await _projectsService.GetAllAsync();
                return Page();
            }

            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnGetProjectDetailsAsync(int? id)
        {
            var project = (id == null) ? new ProjectDTO() : (await _projectsService.GetAsync((int)id)).Data;
            
            return await GetPartialViewAsync(project);
        }

        public async Task<PartialViewResult> OnPostProjectDetails(ProjectDTO project)
        {
            if (ModelState.IsValid)
            {
                var response = (project.Id == 0) ? await _projectsService.CreateAsync(project) : await _projectsService.UpdateAsync(project);
                if (!response.Success)
                {
                    foreach (var error in response.ValidationErrors)
                    {
                        ModelState.AddModelError(error.Key, error.Value);
                    }
                }
            }

            return await GetPartialViewAsync(project);
        }

        private async Task<PartialViewResult> GetPartialViewAsync(ProjectDTO project)
        {
            var stages = (await _stagesService.GetAllAsync(1, 0)).Data.Collection;
            var stagesItems = stages.Select(x => new SelectListItem()
            {
                Value = x.Id.ToString(),
                Text = $"({x.Sign.Trim()}) {x.Title.Trim()}"
            }).ToList();

            if(project.StageId != 0)
            {
                var currentStage = stages.FirstOrDefault(x => x.Id == project.StageId);
                project.StageSign = currentStage.Sign;
                project.StageTitle = currentStage.Title;
            }

            var viewModel = new NewProjectViewModel { Project = project, Stages = stagesItems };

            return new PartialViewResult
            {
                ViewName = partialViewName,
                ViewData = new ViewDataDictionary<NewProjectViewModel>(ViewData, viewModel)
            };
        }
    }
}

SODP.UI/Pages/ActiveProjects/Info.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SODP.Domain.DTO;
using SODP.Domain.Services;
using SODP.UI.Pages.Shared;

namespace SODP.UI.Pages.ActiveProjects
{
    [Authorize(Roles = "Administrator,ProjectManager")]
    public class InfoModel : SODPPageModel
    {
        private readonly IProjectsService _projectsService;

        public InfoModel(IProjectsService projectsService)
        {
            _projectsService = projectsService;
        }

        public ProjectDTO Project { get; set; }
        public IList<string> Branches { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            var response = await _projectsService.GetAsync(id);
            Project = response.Data;

            return Page();
        }
    }
}

SODP.UI/Pages/ActiveProjects/CreateUpdate.cshtml
@page
@model SODP.UI.Pages.ActiveProjects.CreateUpdateModel

<br />
<div class="container row p-0 m-0">
    <div class="col-8">
        <h2 class="text-info">@(Model.Project.Id.Equals(0) ? "Nowy projekt" : "Edycja projektu")</h2>
    </div>
</div>
<div class="container border" style="padding:30px;">
    <form method="post">
        <input name="IsValidate" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
        <input type="hidden" asp-for="Project.Id" />

        <div class="form-group row">
            <div class="col-12 col-md-7">
                <input asp-for="Project.Number" class="form-control" readonly="@(Model.Project.Id.Equals(0) ? false : true)" placeholder="Numer" />
                <span asp-validation-for="Project.Number" style="font-size:14px" class="text-danger"></span>
            </div>
            <div class="row">
            </div>
        </div>

        @if (Model.Project.Id.Equals(0))
        {
            <div class="form-group row">
                <div class="col-12 col-md-7">
                    @Html.DropDownListFor(model => model.Project.StageId, @Model.Stages, "-- Stadium --", new { @class = "form-control" })
                    <span asp-validation-for="@Model.Project.StageId" style="font-size:14px" class="text-danger"></span>
                </div>
            </div>
        }
        else
        {
            <input type="hidden" asp-for="Project.StageId" />
            <div class="form-group row">
                <div class="col-12 col-md-7">
                    <input asp-for="Project.StageTitle" class="form-control" readonly="@(true)" />
                </div>
            </div>
        }

        <div class="form-group row">
            <div class="col-12 col-md-7">
                <input asp-for="Project.Title" class="form-control" placeholder="Tytuł" />
                <span asp-validation-for="Project.Title" style="font-size:14px" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-12 col-md-7">
                <textarea asp-for="Project.Description" class="form-control" placeholder="Opis (opcjonalny)"></textarea>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-12 col-md-7">
                <partial name="_SubmitAndBackButtonPartial" />
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="/Pages/Shared/_ValidationScriptsPartial.cshtml" />
}

SODP.UI/Pages/ActiveProjects/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Projekty aktywne";
}
@using Microsoft.AspNetCore.Identity
@using SODP.Model
@using SODP.UI.ViewModels;

@inject SignInManager<User> SignInManager

<link rel="stylesheet" href="~/lib/DataTables/DataTables-1.10.24/css/jquery.dataTables.min.css" />
<link rel="stylesheet" href="~/lib/DataTables/DataTables-1.10.24/css/dataTables.bootstrap4.min.css" />
<link rel="stylesheet" href="~/lib/DataTables/Buttons-1.7.0/css/buttons.bootstrap4.min.css" />

<br />
<div class="container row p-0 m-0">
    <div class="col-9">
        <h2 class="text-info">@ViewData["Title"]</h2>
    </div>
    @if (User.IsInRole("Administrator") || User.IsInRole("ProjectManager"))
    {
        <div id="modal-placeholder"></div>
        <div class="col-3 justify-content-end">
            <button type="button"
                    class="btn btn-info form-control text-white float-right"
                    title="Nowy projekt"
                    data-toggle="ajax-modal"
                    data-url="@Url.Page("Index","ProjectDetails")">
                <i class="fas fa-plus"></i>&nbsp;&nbsp;&nbsp;Nowy projekt
            </button>
        </div>
    }

    <div class="col-12">
        <table id="ProjectDataTable" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Numer</th>
                    <th>Stadium</th>
                    <th>Tytuł</th>
                    <th></th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Numer</th>
                    <th>Stadium</th>
                    <th>Tytuł</th>
                    <th></th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

@section Scripts{
    <script src="~/js/delete.js"></script>
    <script src="~/js/archive.js"></script>
    <script src="~/js/activeProjectList.js"></script>

    <script src="~/lib/DataTables/DataTables-1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/DataTables/Buttons-1.7.0/js/dataTables.buttons.min.js"></script>

    <script>
        var RoleCheck = @(User.IsInRole("ProjectManager") ? "true" : "false");
        var ProjectsArray = @Json.Serialize(Model.Projects.Data.Collection);
    </script>

    <script>
        function OpenProjectEdit(currentId) {
            $.ajax({
                type: "Get",
                url: '@Url.Page("Index","ProjectDetails")&Id=' + currentId,
                success: function (data) {
                    $('#modal-placeholder').html(data);
                    $('#editproject').modal('show');
                }
            })
        }
    </script>
}

SODP.UI/Pages/ActiveProjects/Info.cshtml
@page
@model SODP.UI.Pages.ActiveProjects.InfoModel
@{
}

SODP.UI/Pages/ActiveProjects/_ProjectPartialView.cshtml
@using SODP.UI.ViewModels
@model NewProjectViewModel
<!-- Modal -->
<div class="modal fade" id="editproject" tabindex="-1" role="dialog" aria-labelledby="editProjectLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="text-info" id="editProjectLabel">@(Model.Project.Id==0 ? "Nowy projekt" : "Edycja projektu")</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                <div id="error-placeholder"></div>
                <form asp-page-handler="ProjectDetails">
                    <input name="IsValidate" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <input asp-for="Project.Id" id="id" type="hidden" value="@Model.Project.Id" />
                    <div class="form-group">
                        <input asp-for="Project.Number" id="number" class="form-control" value="@Model.Project.Number" placeholder="Numer projektu" readonly="@(Model.Project.Id.Equals(0) ? false : true)" />
                        <span asp-validation-for="Project.Number" class="text-danger"></span>
                    </div>

                    @if (Model.Project.Id.Equals(0))
                    {
                        <div class="form-group">
                            @Html.DropDownListFor(model => model.Project.StageId, @Model.Stages, "-- Stadium --", new { @class = "form-control" })
                            <span asp-validation-for="@Model.Project.StageId" style="font-size:14px" class="text-danger"></span>
                        </div>
                    }
                    else
                    {
                        <input type="hidden" asp-for="Project.StageId" />
                        <div class="form-group">
                            <input asp-for="Project.Stage" class="form-control" readonly="@(true)" />
                        </div>
                    }

                    <div class="form-group">
                        <input asp-for="Project.Title" class="form-control" placeholder="Tytuł" />
                        <span asp-validation-for="Project.Title" style="font-size:14px" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <textarea asp-for="Project.Description" class="form-control" placeholder="Opis (opcjonalny)"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <partial name="_SubmitAndBackButtonModalPartial" />
            </div>
        </div>
    </div>
</div>